"""
This type stub file was generated by pyright.
"""

from functools import singledispatch
from dishka import AsyncContainer, Container
from ..async_container import AsyncContainerType
from ..container import ContainerType

@singledispatch
def dishka_setup(app: object, container: Container | AsyncContainer, *args: object, **kwargs: object) -> None:
    ...

@singledispatch
def get_container_(app: object) -> ContainerType | AsyncContainerType:
    ...

