"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from dishka import AsyncContainer
from ..async_container import AsyncContainerType
from ._dispatch import get_container_
from aiogram import Router

if find_spec("aiogram"):
    _setup_dishka = ...
    def setup_dishka(container: AsyncContainer, router: Router, *args: object, **kwargs: object) -> None:
        ...
    
    @get_container_.register(Router)
    def get_container(router: Router) -> AsyncContainerType:
        ...
    
