"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from ..async_container import AsyncContainerType
from ._dispatch import get_container_
from aiohttp.web_app import Application

if find_spec("aiohttp"):
    setup_dishka = ...
    @get_container_.register(Application)
    def get_container(app: Application) -> AsyncContainerType:
        ...
    
