"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from typing import Any
from ..async_container import AsyncContainerType
from ._dispatch import get_container_
from arq import Worker

if find_spec("arq"):
    setup_dishka = ...
    @get_container_.register(dict)
    @get_container_.register(Worker)
    def get_container(worker_setting: dict[Any, Any] | Worker | Any) -> AsyncContainerType:
        ...
    
