"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from ..container import ContainerType
from ._dispatch import get_container_
from celery import Celery

if find_spec("celery"):
    setup_dishka = ...
    @get_container_.register(Celery)
    def get_container(app: Celery) -> ContainerType:
        ...
    
