"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from ..container import ContainerType
from ._dispatch import get_container_
from click import Context

if find_spec("click"):
    setup_dishka = ...
    @get_container_.register(Context)
    def get_container(context: Context) -> ContainerType:
        ...
    
