"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from ..async_container import AsyncContainerType
from ..container import ContainerType
from ._dispatch import get_container_
from fastapi import FastAPI

if find_spec("fastapi"):
    setup_dishka = ...
    @get_container_.register(FastAPI)
    def get_container(app: FastAPI) -> ContainerType | AsyncContainerType:
        ...
    
