"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from dishka import Container
from ..container import ContainerType
from ._dispatch import get_container_
from flask import Flask

if find_spec("flask"):
    _setup_dishka = ...
    def setup_dishka(container: Container, app: Flask, *args: object, **kwargs: object): # -> None:
        ...
    
    @get_container_.register(Flask)
    def get_container(app: Flask) -> ContainerType:
        ...
    
