"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from ..async_container import AsyncContainerType
from ._dispatch import get_container_
from litestar import Litestar

if find_spec("litestar"):
    setup_dishka = ...
    @get_container_.register(Litestar)
    def get_container(app: Litestar) -> AsyncContainerType:
        ...
    
