"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from typing import Any
from dishka import AsyncContainer
from ..async_container import AsyncContainerType
from ._dispatch import get_container_
from sanic import Sanic

if find_spec("sanic"):
    _setup_dishka = ...
    def setup_dishka(container: AsyncContainer, app: Sanic[Any, Any], *args: object, **kwargs: object): # -> None:
        ...
    
    @get_container_.register(Sanic)
    def get_container(app: Sanic[Any, Any]) -> AsyncContainerType:
        ...
    
