"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from ..async_container import AsyncContainerType
from ._dispatch import get_container_
from starlette.applications import Starlette

if find_spec("starlette"):
    setup_dishka = ...
    @get_container_.register(Starlette)
    def get_container(app: Starlette) -> AsyncContainerType:
        ...
    
