"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from dishka import AsyncContainer
from ..async_container import AsyncContainerType
from ._dispatch import get_container_
from taskiq import AsyncBroker

if find_spec("taskiq"):
    _setup_dishka = ...
    def setup_dishka(container: AsyncContainer, broker: AsyncBroker, *args: object, **kwargs: object) -> None:
        ...
    
    @get_container_.register(AsyncBroker)
    def get_container(broker: AsyncBroker) -> AsyncContainerType:
        ...
    
