"""
This type stub file was generated by pyright.
"""

from importlib.util import find_spec
from dishka import Container
from ..container import ContainerType
from ._dispatch import get_container_
from telebot import TeleBot

if find_spec("telebot"):
    _setup_dishka = ...
    def setup_dishka(container: Container, bot: TeleBot, *args: object, **kwargs: object): # -> None:
        ...
    
    @get_container_.register(TeleBot)
    def get_container(bot: TeleBot) -> ContainerType:
        ...
    
