"""
This type stub file was generated by pyright.
"""

import os
import concurrent.futures
from kombu.utils.imports import symbol_by_name

"""Pool implementation abstract factory, and alias definitions."""
__all__ = ('get_implementation', 'get_available_pool_names')
ALIASES = ...
custom = ...
def get_implementation(cls): # -> Any | ModuleType:
    """Return pool implementation by name."""
    ...

def get_available_pool_names(): # -> tuple[str, ...]:
    """Return all available pool type names."""
    ...

