"""
This type stub file was generated by pyright.
"""

from typing import Iterator, TYPE_CHECKING
from cryptography.hazmat.primitives.asymmetric.dsa import DSAPublicKey
from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurvePublicKey
from cryptography.hazmat.primitives.asymmetric.ed448 import Ed448PublicKey
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicKey
from cryptography.hazmat.primitives.asymmetric.utils import Prehashed
from cryptography.hazmat.primitives.hashes import HashAlgorithm

"""X.509 certificates."""
if TYPE_CHECKING:
    ...
__all__ = ('Certificate', 'CertStore', 'FSCertStore')
class Certificate:
    """X.509 certificate."""
    def __init__(self, cert: str) -> None:
        ...
    
    def has_expired(self) -> bool:
        """Check if the certificate has expired."""
        ...
    
    def get_pubkey(self) -> (DSAPublicKey | EllipticCurvePublicKey | Ed448PublicKey | Ed25519PublicKey | RSAPublicKey):
        ...
    
    def get_serial_number(self) -> int:
        """Return the serial number in the certificate."""
        ...
    
    def get_issuer(self) -> str:
        """Return issuer (CA) as a string."""
        ...
    
    def get_id(self) -> str:
        """Serial number/issuer pair uniquely identifies a certificate."""
        ...
    
    def verify(self, data: bytes, signature: bytes, digest: HashAlgorithm | Prehashed) -> None:
        """Verify signature for string containing data."""
        ...
    


class CertStore:
    """Base class for certificate stores."""
    def __init__(self) -> None:
        ...
    
    def itercerts(self) -> Iterator[Certificate]:
        """Return certificate iterator."""
        ...
    
    def __getitem__(self, id: str) -> Certificate:
        """Get certificate by id."""
        ...
    
    def add_cert(self, cert: Certificate) -> None:
        ...
    


class FSCertStore(CertStore):
    """File system certificate store."""
    def __init__(self, path: str) -> None:
        ...
    


