[project]
name = "ashka"
version = "0.5.0"
description = "Addons for dishka"
readme = "README.md"
authors = [
    { name = "handsome-Druid", email = "102826168@qq.com" }
]
requires-python = ">=3.10,<=3.14"
dependencies = [
    "aiogram>=3.30.0",
    "dishka<=1.10.1,>=1.10.1",
    "taskiq>=0.12.5",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "aiohttp>=3.14.3",
    "celery>=5.6.3",
    "fastapi>=0.141.1",
    "flask>=3.1.3",
    "litestar>=2.24.0",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.16.4",
    "sanic>=25.12.1",
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.coverage.run]
branch = true
patch = ["subprocess"]

[tool.coverage.report]
fail_under = 100

[tool.pytest.ini_options]
addopts = "-n auto"

[tool.ruff]
exclude = ["typings"]

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "first-party",
    "third-party",
    "local-folder",
]
