"""
This type stub file was generated by pyright.
"""

from collections import UserList
from kombu.utils.objects import cached_property

"""Start/stop/manage workers."""
__all__ = ('Cluster', 'Node')
CELERY_EXE = ...
def celery_exe(*args): # -> LiteralString:
    ...

def build_nodename(name, prefix, suffix): # -> tuple[str | Any | None, str, str | Any]:
    ...

def build_expander(nodename, shortname, hostname): # -> partial[str]:
    ...

def format_opt(opt, value): # -> str:
    ...

class NamespacedOptionParser:
    def __init__(self, args) -> None:
        ...
    
    def parse(self): # -> None:
        ...
    
    def process_long_opt(self, arg, value=...): # -> None:
        ...
    
    def process_short_opt(self, arg, value=...): # -> None:
        ...
    
    def optmerge(self, ns, defaults=...): # -> OrderedDict[Any, Any]:
        ...
    
    def add_option(self, name, value, short=..., ns=...): # -> None:
        ...
    


class Node:
    """Represents a node in a cluster."""
    def __init__(self, name, cmd=..., append=..., options=..., extra_args=...) -> None:
        ...
    
    def alive(self): # -> bool | None:
        ...
    
    def send(self, sig, on_error=...): # -> bool | None:
        ...
    
    def start(self, env=..., **kwargs): # -> int:
        ...
    
    def handle_process_exit(self, retcode, on_signalled=..., on_failure=...):
        ...
    
    def prepare_argv(self, argv, path): # -> list[str]:
        ...
    
    def getopt(self, *alt):
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @cached_property
    def pidfile(self): # -> str:
        ...
    
    @cached_property
    def logfile(self): # -> str:
        ...
    
    @property
    def pid(self): # -> int | None:
        ...
    
    @pid.setter
    def pid(self, value): # -> None:
        ...
    
    @cached_property
    def executable(self):
        ...
    
    @cached_property
    def argv_with_executable(self): # -> tuple[Any, *tuple[str, ...], str] | tuple[Any, *tuple[str, ...]]:
        ...
    
    @classmethod
    def from_kwargs(cls, name, **kwargs): # -> Self:
        ...
    


def maybe_call(fun, *args, **kwargs): # -> None:
    ...

class MultiParser:
    Node = Node
    def __init__(self, cmd=..., append=..., prefix=..., suffix=..., range_prefix=...) -> None:
        ...
    
    def parse(self, p): # -> Generator[Node, None, None]:
        ...
    


class Cluster(UserList):
    """Represent a cluster of workers."""
    def __init__(self, nodes, cmd=..., env=..., on_stopping_preamble=..., on_send_signal=..., on_still_waiting_for=..., on_still_waiting_progress=..., on_still_waiting_end=..., on_node_start=..., on_node_restart=..., on_node_shutdown_ok=..., on_node_status=..., on_node_signal=..., on_node_signal_dead=..., on_node_down=..., on_child_spawn=..., on_child_signalled=..., on_child_failure=...) -> None:
        ...
    
    def start(self): # -> list[Any]:
        ...
    
    def start_node(self, node):
        ...
    
    def send_all(self, sig): # -> None:
        ...
    
    def kill(self): # -> None:
        ...
    
    def restart(self, sig=...): # -> list[Any]:
        ...
    
    def stop(self, retry=..., callback=..., sig=...): # -> None:
        ...
    
    def stopwait(self, retry=..., callback=..., sig=...): # -> None:
        ...
    
    def shutdown_nodes(self, nodes, sig=..., retry=...): # -> Generator[Any, Any, None]:
        ...
    
    def find(self, name):
        ...
    
    def getpids(self, on_down=...): # -> Generator[Any, Any, None]:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def data(self): # -> Any:
        ...
    


