"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any, overload
from ashka.entities.scope import AshkaScope
from dishka import BaseScope
from dishka.dependency_source.composite import CompositeDependencySource
from dishka.provider.make_factory import ProvideSource

__all__ = ["provide"]
@overload
def provide(*, scope: BaseScope | AshkaScope | None = ..., **kwargs: Any) -> Callable[[Callable[..., Any]], CompositeDependencySource]:
    ...

@overload
def provide(source: ProvideSource, *, scope: BaseScope | AshkaScope | None = ..., **kwargs: Any) -> CompositeDependencySource:
    ...

def provide(source: ProvideSource | None = ..., *, scope: BaseScope | AshkaScope | None = ..., **kwargs: Any) -> (CompositeDependencySource | Callable[[Callable[..., Any]], CompositeDependencySource,]):
    ...

