"""
This type stub file was generated by pyright.
"""

from logging import getLogger
from os import getenv
from sys import modules
from . import integrations as integrations
from .async_container import make_async_container
from .container import make_container
from .entities.scope import BOOTSTRAP
from .provider import provide

__all__ = ["BOOTSTRAP", "make_async_container", "make_container", "provide"]
if "dishka" in modules and getenv(env := "ASHKA_DISABLE_IMPORT_WARNING", "").strip().lower() not in ("1", "true", "yes", "on"):
    ...
