"""
This type stub file was generated by pyright.
"""

from typing import Any
from dishka import AsyncContainer
from dishka.provider import BaseProvider

__all__ = ["make_async_container"]
_aenter = ...
async def __aenter__(self: AsyncContainer): # -> AsyncContainer:
    ...

class AsyncContainerType(AsyncContainer):
    __slots__ = ...
    __aenter__ = ...
    async def init(self) -> None:
        ...
    


_make_async_container = ...
def make_async_container(*providers: BaseProvider, **kwargs: Any) -> AsyncContainerType:
    ...

