"""
This type stub file was generated by pyright.
"""

from typing import Any
from dishka import Container
from dishka.provider import BaseProvider

__all__ = ["make_container"]
_enter = ...
def __enter__(self: Container): # -> Container:
    ...

class ContainerType(Container):
    __slots__ = ...
    __enter__ = ...
    def init(self) -> None:
        ...
    


_make_container = ...
def make_container(*providers: BaseProvider, **kwargs: Any) -> ContainerType:
    ...

