"""
This type stub file was generated by pyright.
"""

from celery.exceptions import TimeoutError

"""Result backend base classes.

- :class:`BaseBackend` defines the interface.

- :class:`KeyValueStoreBackend` is a common base class
    using K/V semantics like _get and _put.
"""
__all__ = ('BaseBackend', 'KeyValueStoreBackend', 'DisabledBackend')
EXCEPTION_ABLE_CODECS = ...
logger = ...
MESSAGE_BUFFER_MAX = ...
pending_results_t = ...
E_NO_BACKEND = ...
E_CHORD_NO_BACKEND = ...
def unpickle_backend(cls, args, kwargs):
    """Return an unpickled backend."""
    ...

class _nulldict(dict):
    def ignore(self, *a, **kw): # -> None:
        ...
    
    setdefault = ...


class Backend:
    READY_STATES = ...
    UNREADY_STATES = ...
    EXCEPTION_STATES = ...
    TimeoutError = TimeoutError
    subpolling_interval = ...
    supports_native_join = ...
    supports_autoexpire = ...
    persistent = ...
    retry_policy = ...
    def __init__(self, app, serializer=..., max_cached_results=..., accept=..., expires=..., expires_type=..., url=..., **kwargs) -> None:
        ...
    
    def as_uri(self, include_password=...): # -> None:
        """Return the backend as an URI, sanitizing the password or not."""
        ...
    
    def mark_as_started(self, task_id, **meta): # -> Any | UnpickleableExceptionWrapper | dict[str, Any]:
        """Mark a task as started."""
        ...
    
    def mark_as_done(self, task_id, result, request=..., store_result=..., state=...): # -> None:
        """Mark task as successfully executed."""
        ...
    
    def mark_as_failure(self, task_id, exc, traceback=..., request=..., store_result=..., call_errbacks=..., state=...): # -> None:
        """Mark task as executed with failure."""
        ...
    
    def mark_as_revoked(self, task_id, reason=..., request=..., store_result=..., state=...): # -> None:
        ...
    
    def mark_as_retry(self, task_id, exc, traceback=..., request=..., store_result=..., state=...): # -> Any | UnpickleableExceptionWrapper | dict[str, Any]:
        """Mark task as being retries.

        Note:
            Stores the current exception (if any).
        """
        ...
    
    def chord_error_from_stack(self, callback, exc=...): # -> ExceptionInfo | None:
        ...
    
    def fail_from_current_stack(self, task_id, exc=...): # -> ExceptionInfo:
        ...
    
    def prepare_exception(self, exc, serializer=...): # -> Any | UnpickleableExceptionWrapper | dict[str, Any]:
        """Prepare exception for serialization."""
        ...
    
    def exception_to_python(self, exc): # -> Any | BaseException | Exception | None:
        """Convert serialized exception to Python exception."""
        ...
    
    def prepare_value(self, result):
        """Prepare value for storage."""
        ...
    
    def encode(self, data): # -> bytes:
        ...
    
    def meta_from_decoded(self, meta):
        ...
    
    def decode_result(self, payload): # -> str | None:
        ...
    
    def decode(self, payload): # -> str | None:
        ...
    
    def prepare_expires(self, value, type=...): # -> float | None:
        ...
    
    def prepare_persistent(self, enabled=...): # -> bool:
        ...
    
    def encode_result(self, result, state): # -> Any | UnpickleableExceptionWrapper | dict[str, Any]:
        ...
    
    def is_cached(self, task_id): # -> bool:
        ...
    
    def store_result(self, task_id, result, state, traceback=..., request=..., **kwargs): # -> Any | UnpickleableExceptionWrapper | dict[str, Any]:
        """Update task state and result.

        if always_retry_backend_operation is activated, in the event of a recoverable exception,
        then retry operation with an exponential backoff until a limit has been reached.
        """
        ...
    
    def forget(self, task_id): # -> None:
        ...
    
    def get_state(self, task_id):
        """Get the state of a task."""
        ...
    
    get_status = ...
    def get_traceback(self, task_id):
        """Get the traceback for a failed task."""
        ...
    
    def get_result(self, task_id):
        """Get the result of a task."""
        ...
    
    def get_children(self, task_id): # -> None:
        """Get the list of subtasks sent by a task."""
        ...
    
    def exception_safe_to_retry(self, exc): # -> Literal[False]:
        """Check if an exception is safe to retry.

        Backends have to overload this method with correct predicates dealing with their exceptions.

        By default no exception is safe to retry, it's up to backend implementation
        to define which exceptions are safe.
        """
        ...
    
    def on_backend_retryable_error(self, exc): # -> None:
        """Hook called before retrying a recoverable backend exception."""
        ...
    
    def get_task_meta(self, task_id, cache=...):
        """Get task meta from backend.

        if always_retry_backend_operation is activated, in the event of a recoverable exception,
        then retry operation with an exponential backoff until a limit has been reached.
        """
        ...
    
    def reload_task_result(self, task_id): # -> None:
        """Reload task result, even if it has been previously fetched."""
        ...
    
    def reload_group_result(self, group_id): # -> None:
        """Reload group result, even if it has been previously fetched."""
        ...
    
    def get_group_meta(self, group_id, cache=...): # -> None:
        ...
    
    def restore_group(self, group_id, cache=...): # -> None:
        """Get the result for a group."""
        ...
    
    def save_group(self, group_id, result):
        """Store the result of an executed group."""
        ...
    
    def delete_group(self, group_id):
        ...
    
    def cleanup(self): # -> None:
        """Backend cleanup."""
        ...
    
    def process_cleanup(self): # -> None:
        """Cleanup actions to do at the end of a task worker process."""
        ...
    
    def on_task_call(self, producer, task_id): # -> dict[Any, Any]:
        ...
    
    def add_to_chord(self, chord_id, result):
        ...
    
    def on_chord_part_return(self, request, state, result, **kwargs): # -> None:
        ...
    
    def set_chord_size(self, group_id, chord_size): # -> None:
        ...
    
    def fallback_chord_unlock(self, header_result, body, countdown=..., **kwargs): # -> None:
        ...
    
    def ensure_chords_allowed(self): # -> None:
        ...
    
    def apply_chord(self, header_result_args, body, **kwargs): # -> None:
        ...
    
    def current_task_children(self, request=...): # -> list[Any] | None:
        ...
    
    def __reduce__(self, args=..., kwargs=...): # -> tuple[Callable[..., Any], tuple[type[Self], Any, Any | dict[Any, Any]]]:
        ...
    


class SyncBackendMixin:
    def iter_native(self, result, timeout=..., interval=..., no_ack=..., on_message=..., on_interval=...): # -> Generator[tuple[Any, Any | None] | Any, Any, None]:
        ...
    
    def wait_for_pending(self, result, timeout=..., interval=..., no_ack=..., on_message=..., on_interval=..., callback=..., propagate=...): # -> None:
        ...
    
    def wait_for(self, task_id, timeout=..., interval=..., no_ack=..., on_interval=...):
        """Wait for task and return its result.

        If the task raises an exception, this exception
        will be re-raised by :func:`wait_for`.

        Raises:
            celery.exceptions.TimeoutError:
                If `timeout` is not :const:`None`, and the operation
                takes longer than `timeout` seconds.
        """
        ...
    
    def add_pending_result(self, result, weak=...):
        ...
    
    def remove_pending_result(self, result):
        ...
    
    @property
    def is_async(self): # -> Literal[False]:
        ...
    


class BaseBackend(Backend, SyncBackendMixin):
    """Base (synchronous) result backend."""
    ...


BaseDictBackend = BaseBackend
class BaseKeyValueStoreBackend(Backend):
    key_t = ...
    task_keyprefix = ...
    group_keyprefix = ...
    chord_keyprefix = ...
    implements_incr = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get(self, key):
        ...
    
    def mget(self, keys):
        ...
    
    def set(self, key, value):
        ...
    
    def delete(self, key):
        ...
    
    def incr(self, key):
        ...
    
    def expire(self, key, value): # -> None:
        ...
    
    def get_key_for_task(self, task_id, key=...): # -> bytes | str | Any:
        """Get the cache key for a task by id."""
        ...
    
    def get_key_for_group(self, group_id, key=...): # -> bytes | str | Any:
        """Get the cache key for a group by id."""
        ...
    
    def get_key_for_chord(self, group_id, key=...): # -> bytes | str | Any:
        """Get the cache key for the chord waiting on group with given id."""
        ...
    
    def get_many(self, task_ids, timeout=..., interval=..., no_ack=..., on_message=..., on_interval=..., max_iterations=..., READY_STATES=...): # -> Generator[tuple[str | Any, Any] | tuple[str | Any, Any | str | None], Any, None]:
        ...
    
    def on_chord_part_return(self, request, state, result, **kwargs): # -> ExceptionInfo | None:
        ...
    


class KeyValueStoreBackend(BaseKeyValueStoreBackend, SyncBackendMixin):
    """Result backend base class for key/value stores."""
    ...


class DisabledBackend(BaseBackend):
    """Dummy result backend."""
    _cache = ...
    def store_result(self, *args, **kwargs): # -> None:
        ...
    
    def ensure_chords_allowed(self):
        ...
    
    def as_uri(self, *args, **kwargs): # -> Literal['disabled://']:
        ...
    
    get_traceback = ...
    get_many = ...


