"""
This type stub file was generated by pyright.
"""

"""Utility to dump events to screen.

This is a simple program that dumps events to the console
as they happen.  Think of it like a `tcpdump` for Celery events.
"""
__all__ = ('Dumper', 'evdump')
TASK_NAMES = ...
HUMAN_TYPES = ...
CONNECTION_ERROR = ...
def humanize_type(type): # -> str:
    ...

class Dumper:
    """Monitor events."""
    def __init__(self, out=...) -> None:
        ...
    
    def say(self, msg): # -> None:
        ...
    
    def on_event(self, ev): # -> None:
        ...
    
    def format_task_event(self, hostname, timestamp, type, task, event): # -> None:
        ...
    


def evdump(app=..., out=...):
    """Start event dump."""
    ...

if __name__ == '__main__':
    ...
