"""
This type stub file was generated by pyright.
"""

from kombu.mixins import ConsumerMixin

"""Event receiver implementation."""
__all__ = ('EventReceiver', )
CLIENT_CLOCK_SKEW = ...
_TZGETTER = ...
class EventReceiver(ConsumerMixin):
    """Capture events.

    Arguments:
        connection (kombu.Connection): Connection to the broker.
        handlers (Mapping[Callable]): Event handlers.
            This is  a map of event type names and their handlers.
            The special handler `"*"` captures all events that don't have a
            handler.
    """
    app = ...
    def __init__(self, channel, handlers=..., routing_key=..., node_id=..., app=..., queue_prefix=..., accept=..., queue_ttl=..., queue_expires=..., queue_exclusive=..., queue_durable=...) -> None:
        ...
    
    def process(self, type, event): # -> None:
        """Process event by dispatching to configured handler."""
        ...
    
    def get_consumers(self, Consumer, channel): # -> list[Any]:
        ...
    
    def on_consume_ready(self, connection, channel, consumers, wakeup=..., **kwargs): # -> None:
        ...
    
    def itercapture(self, limit=..., timeout=..., wakeup=...): # -> Generator[None, Any, None]:
        ...
    
    def capture(self, limit=..., timeout=..., wakeup=...): # -> None:
        """Open up a consumer capturing events.

        This has to run in the main process, and it will never stop
        unless :attr:`EventDispatcher.should_stop` is set to True, or
        forced via :exc:`KeyboardInterrupt` or :exc:`SystemExit`.
        """
        ...
    
    def wakeup_workers(self, channel=...): # -> None:
        ...
    
    def event_from_message(self, body, localize=..., now=..., tzfields=..., adjust_timestamp=..., CLIENT_CLOCK_SKEW=...): # -> tuple[Any | Literal['task-sent'], Any]:
        ...
    
    @property
    def connection(self): # -> None:
        ...
    


