"""
This type stub file was generated by pyright.
"""

from kombu.utils.objects import cached_property
from celery.concurrency.base import BasePool

"""Task request.

This module defines the :class:`Request` class, that specifies
how tasks are executed.
"""
__all__ = ('Request', )
IS_PYPY = ...
logger = ...
_does_info = ...
_does_debug = ...
def __optimize__(): # -> None:
    ...

tz_or_local = ...
send_revoked = ...
send_retry = ...
task_accepted = ...
task_ready = ...
revoked_tasks = ...
revoked_stamps = ...
class Request:
    """A request for task execution."""
    acknowledged = ...
    time_start = ...
    worker_pid = ...
    time_limits = ...
    _already_revoked = ...
    _already_cancelled = ...
    _terminate_on_ack = ...
    _apply_result = ...
    _tzlocal = ...
    if not IS_PYPY:
        __slots__ = ...
    def __init__(self, message, on_ack=..., hostname=..., eventer=..., app=..., connection_errors=..., request_dict=..., task=..., on_reject=..., body=..., headers=..., decoded=..., utc=..., maybe_make_aware=..., maybe_iso8601=..., **opts) -> None:
        ...
    
    @property
    def delivery_info(self): # -> dict[str, Any]:
        ...
    
    @property
    def message(self): # -> Any:
        ...
    
    @property
    def request_dict(self):
        ...
    
    @property
    def body(self):
        ...
    
    @property
    def app(self): # -> None:
        ...
    
    @property
    def utc(self): # -> bool:
        ...
    
    @property
    def content_type(self): # -> None:
        ...
    
    @property
    def content_encoding(self): # -> None:
        ...
    
    @property
    def type(self):
        ...
    
    @property
    def root_id(self):
        ...
    
    @property
    def parent_id(self):
        ...
    
    @property
    def argsrepr(self):
        ...
    
    @property
    def args(self):
        ...
    
    @property
    def kwargs(self):
        ...
    
    @property
    def kwargsrepr(self):
        ...
    
    @property
    def on_ack(self):
        ...
    
    @property
    def on_reject(self):
        ...
    
    @on_reject.setter
    def on_reject(self, value): # -> None:
        ...
    
    @property
    def hostname(self):
        ...
    
    @property
    def ignore_result(self):
        ...
    
    @property
    def eventer(self): # -> None:
        ...
    
    @eventer.setter
    def eventer(self, eventer): # -> None:
        ...
    
    @property
    def connection_errors(self): # -> tuple[()]:
        ...
    
    @property
    def task(self):
        ...
    
    @property
    def eta(self): # -> None:
        ...
    
    @property
    def expires(self): # -> None:
        ...
    
    @expires.setter
    def expires(self, value): # -> None:
        ...
    
    @property
    def tzlocal(self):
        ...
    
    @property
    def store_errors(self): # -> Literal[True]:
        ...
    
    @property
    def task_id(self):
        ...
    
    @task_id.setter
    def task_id(self, value): # -> None:
        ...
    
    @property
    def task_name(self):
        ...
    
    @task_name.setter
    def task_name(self, value): # -> None:
        ...
    
    @property
    def reply_to(self):
        ...
    
    @property
    def replaced_task_nesting(self):
        ...
    
    @property
    def groups(self):
        ...
    
    @property
    def stamped_headers(self) -> list:
        ...
    
    @property
    def stamps(self) -> dict:
        ...
    
    @property
    def correlation_id(self):
        ...
    
    def execute_using_pool(self, pool: BasePool, **kwargs): # -> None:
        """Used by the worker to send this task to the pool.

        Arguments:
            pool (~celery.concurrency.base.TaskPool): The execution pool
                used to execute this request.

        Raises:
            celery.exceptions.TaskRevokedError: if the task was revoked.
        """
        ...
    
    def execute(self, loglevel=..., logfile=...): # -> None:
        """Execute the task in a :func:`~celery.app.trace.trace_task`.

        Arguments:
            loglevel (int): The loglevel used by the task.
            logfile (str): The logfile used by the task.
        """
        ...
    
    def maybe_expire(self): # -> Literal[True] | None:
        """If expired, mark the task as revoked."""
        ...
    
    def terminate(self, pool, signal=...): # -> None:
        ...
    
    def cancel(self, pool, signal=..., emit_retry=...): # -> None:
        ...
    
    def revoked(self): # -> bool:
        """If revoked, skip task and mark state."""
        ...
    
    def send_event(self, type, **fields): # -> None:
        ...
    
    def on_accepted(self, pid, time_accepted): # -> None:
        """Handler called when task is accepted by worker pool."""
        ...
    
    def on_timeout(self, soft, timeout): # -> None:
        """Handler called if the task times out."""
        ...
    
    def on_success(self, failed__retval__runtime, **kwargs): # -> None:
        """Handler called if the task was successfully processed."""
        ...
    
    def on_retry(self, exc_info): # -> None:
        """Handler called if the task should be retried."""
        ...
    
    def on_failure(self, exc_info, send_failed_event=..., return_ok=...): # -> None:
        """Handler called if the task raised an exception."""
        ...
    
    def acknowledge(self): # -> None:
        """Acknowledge task."""
        ...
    
    def reject(self, requeue=...): # -> None:
        ...
    
    def info(self, safe=...): # -> dict[str, Any]:
        ...
    
    def humaninfo(self): # -> str:
        ...
    
    def __str__(self) -> str:
        """``str(self)``."""
        ...
    
    def __repr__(self): # -> str:
        """``repr(self)``."""
        ...
    
    @cached_property
    def chord(self):
        ...
    
    @cached_property
    def errbacks(self):
        ...
    
    @cached_property
    def group(self):
        ...
    
    @cached_property
    def group_index(self):
        ...
    


def create_request_cls(base, task, pool, hostname, eventer, ref=..., revoked_tasks=..., task_ready=..., trace=..., app=...): # -> type[Request]:
    class Request(base):
        ...
    
    

