"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod
from collections.abc import Callable

"""Abstract classes."""
__all__ = ('CallableTask', 'CallableSignature')
class _AbstractClass(metaclass=ABCMeta):
    __required_attributes__ = ...
    @classmethod
    def register(cls, other):
        ...
    


class CallableTask(_AbstractClass, Callable):
    """Task interface."""
    __required_attributes__ = ...
    @abstractmethod
    def delay(self, *args, **kwargs): # -> None:
        ...
    
    @abstractmethod
    def apply_async(self, *args, **kwargs): # -> None:
        ...
    
    @abstractmethod
    def apply(self, *args, **kwargs): # -> None:
        ...
    
    @classmethod
    def __subclasshook__(cls, C): # -> NotImplementedType | Literal[True]:
        ...
    


class CallableSignature(CallableTask):
    """Celery Signature interface."""
    __required_attributes__ = ...
    @property
    @abstractmethod
    def name(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def type(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def app(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def id(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def task(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def args(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def kwargs(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def options(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def subtask_type(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def chord_size(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def immutable(self): # -> None:
        ...
    
    @abstractmethod
    def clone(self, args=..., kwargs=...): # -> None:
        ...
    
    @abstractmethod
    def freeze(self, id=..., group_id=..., chord=..., root_id=..., group_index=...): # -> None:
        ...
    
    @abstractmethod
    def set(self, immutable=..., **options): # -> None:
        ...
    
    @abstractmethod
    def link(self, callback): # -> None:
        ...
    
    @abstractmethod
    def link_error(self, errback): # -> None:
        ...
    
    @abstractmethod
    def __or__(self, other): # -> None:
        ...
    
    @abstractmethod
    def __invert__(self): # -> None:
        ...
    
    @classmethod
    def __subclasshook__(cls, C): # -> NotImplementedType | Literal[True]:
        ...
    


