"""
This type stub file was generated by pyright.
"""

import typing

"""Code related to handling annotations."""
def is_none_type(value: typing.Any) -> bool:
    """Check if the given value is a NoneType."""
    ...

def get_optional_arg(annotation: typing.Any) -> typing.Any:
    """Get the argument from an Optional[...] annotation, or None if it is no such annotation."""
    ...

def annotation_is_class(annotation: typing.Any) -> bool:
    """Test if a given annotation is a class that can be used in isinstance()/issubclass()."""
    ...

def annotation_issubclass(annotation: typing.Any, cls: type) -> bool:
    """Test if a given annotation is of the given subclass."""
    ...

