"""
This type stub file was generated by pyright.
"""

from kombu.entity import Queue

"""Worker name utilities."""
WORKER_DIRECT_EXCHANGE = ...
WORKER_DIRECT_QUEUE_FORMAT = ...
NODENAME_SEP = ...
NODENAME_DEFAULT = ...
gethostname = ...
__all__ = ('worker_direct', 'gethostname', 'nodename', 'anon_nodename', 'nodesplit', 'default_nodename', 'node_format', 'host_format')
def worker_direct(hostname: str | Queue) -> Queue:
    """Return the :class:`kombu.Queue` being a direct route to a worker.

    Arguments:
        hostname (str, ~kombu.Queue): The fully qualified node name of
            a worker (e.g., ``w1@example.com``).  If passed a
            :class:`kombu.Queue` instance it will simply return
            that instead.
    """
    ...

def nodename(name: str, hostname: str) -> str:
    """Create node name from name/hostname pair."""
    ...

def anon_nodename(hostname: str | None = ..., prefix: str = ...) -> str:
    """Return the nodename for this process (not a worker).

    This is used for e.g. the origin task message field.
    """
    ...

def nodesplit(name: str) -> tuple[None, str] | list[str]:
    """Split node name into tuple of name/hostname."""
    ...

def default_nodename(hostname: str) -> str:
    """Return the default nodename for this process."""
    ...

def node_format(s: str, name: str, **extra: dict) -> str:
    """Format worker node name (name@host.com)."""
    ...

_fmt_process_index_with_prefix = ...
def host_format(s: str, host: str | None = ..., name: str | None = ..., **extra: dict) -> str:
    """Format host %x abbreviations."""
    ...

