"""
This type stub file was generated by pyright.
"""

def detect_quorum_queues(app, driver_type: str) -> tuple[bool, str]:
    """Detect if any of the queues are quorum queues.

    Returns:
        tuple[bool, str]: A tuple containing a boolean indicating if any of the queues are quorum queues
        and the name of the first quorum queue found or an empty string if no quorum queues were found.
    """
    ...

