"""
This type stub file was generated by pyright.
"""

import threading
from itertools import count
from typing import Any, Callable, Optional
from kombu.asynchronous.timer import Entry, Timer as Schedule

"""Scheduler for Python functions.

.. note::
    This is used for the thread-based worker only,
    not for amqp/redis/sqs/qpid where :mod:`kombu.asynchronous.timer` is used.
"""
TIMER_DEBUG = ...
__all__ = ('Entry', 'Schedule', 'Timer', 'to_timestamp')
class Timer(threading.Thread):
    """Timer thread.

    Note:
        This is only used for transports not supporting AsyncIO.
    """
    Entry = Entry
    Schedule = Schedule
    running: bool = ...
    on_tick: Optional[Callable[[float], None]] = ...
    _timer_count: count = ...
    if TIMER_DEBUG:
        def start(self, *args: Any, **kwargs: Any) -> None:
            ...
        
    def __init__(self, schedule: Optional[Schedule] = ..., on_error: Optional[Callable[[Exception], None]] = ..., on_tick: Optional[Callable[[float], None]] = ..., on_start: Optional[Callable[[Timer], None]] = ..., max_interval: Optional[float] = ..., **kwargs: Any) -> None:
        ...
    
    next = ...
    def run(self) -> None:
        ...
    
    def stop(self) -> None:
        ...
    
    def ensure_started(self) -> None:
        ...
    
    def enter(self, entry: Entry, eta: float, priority: Optional[int] = ...) -> Entry:
        ...
    
    def call_at(self, *args: Any, **kwargs: Any) -> Entry:
        ...
    
    def enter_after(self, *args: Any, **kwargs: Any) -> Entry:
        ...
    
    def call_after(self, *args: Any, **kwargs: Any) -> Entry:
        ...
    
    def call_repeatedly(self, *args: Any, **kwargs: Any) -> Entry:
        ...
    
    def exit_after(self, secs: float, priority: int = ...) -> None:
        ...
    
    def cancel(self, tref: Entry) -> None:
        ...
    
    def clear(self) -> None:
        ...
    
    def empty(self) -> bool:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __bool__(self) -> bool:
        """``bool(timer)``."""
        ...
    
    __nonzero__ = ...
    @property
    def queue(self) -> list:
        ...
    


