"""
This type stub file was generated by pyright.
"""

import sys
import time as _time
from datetime import datetime, timedelta, tzinfo
from types import ModuleType
from typing import Any, Callable
from kombu.utils.objects import cached_property

"""Utilities related to dates, times, intervals, and timezones."""
if sys.version_info >= (3, 9):
    ...
else:
    ...
logger = ...
__all__ = ('LocalTimezone', 'timezone', 'maybe_timedelta', 'delta_resolution', 'remaining', 'rate', 'weekday', 'humanize_seconds', 'maybe_iso8601', 'is_naive', 'make_aware', 'localize', 'to_utc', 'maybe_make_aware', 'ffwd', 'utcoffset', 'adjust_timestamp', 'get_exponential_backoff_interval')
C_REMDEBUG = ...
DAYNAMES = ...
WEEKDAYS = ...
MONTHNAMES = ...
YEARMONTHS = ...
RATE_MODIFIER_MAP = ...
TIME_UNITS = ...
ZERO = ...
_local_timezone = ...
class LocalTimezone(tzinfo):
    """Local time implementation. Provided in _Zone to the app when `enable_utc` is disabled.
    Otherwise, _Zone provides a UTC ZoneInfo instance as the timezone implementation for the application.

    Note:
        Used only when the :setting:`enable_utc` setting is disabled.
    """
    _offset_cache: dict[int, tzinfo] = ...
    def __init__(self) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def utcoffset(self, dt: datetime) -> timedelta:
        ...
    
    def dst(self, dt: datetime) -> timedelta:
        ...
    
    def tzname(self, dt: datetime) -> str:
        ...
    
    def fromutc(self, dt: datetime) -> datetime:
        ...
    


class _Zone:
    """Timezone class that provides the timezone for the application.
    If `enable_utc` is disabled, local system timezone is provided as the timezone provider through local().
    Otherwise, this class provides a UTC ZoneInfo instance as the timezone provider for the application.

    Additionally this class provides a few utility methods for converting datetimes.
    """
    def tz_or_local(self, tzinfo: tzinfo | None = ...) -> tzinfo:
        """Return either our local timezone or the provided timezone."""
        ...
    
    def to_local(self, dt: datetime, local=..., orig=...): # -> datetime:
        """Converts a datetime to the local timezone."""
        ...
    
    def to_system(self, dt: datetime) -> datetime:
        """Converts a datetime to the system timezone."""
        ...
    
    def to_local_fallback(self, dt: datetime) -> datetime:
        """Converts a datetime to the local timezone, or the system timezone."""
        ...
    
    def get_timezone(self, zone: str | tzinfo) -> tzinfo:
        """Returns ZoneInfo timezone if the provided zone is a string, otherwise return the zone."""
        ...
    
    @cached_property
    def local(self) -> tzinfo:
        """Return the local system timezone for the application."""
        ...
    
    @cached_property
    def utc(self) -> tzinfo:
        """Return UTC timezone created with ZoneInfo."""
        ...
    


timezone = ...
def maybe_timedelta(delta: int) -> timedelta:
    """Convert integer to timedelta, if argument is an integer."""
    ...

def delta_resolution(dt: datetime, delta: timedelta) -> datetime:
    """Round a :class:`~datetime.datetime` to the resolution of timedelta.

    If the :class:`~datetime.timedelta` is in days, the
    :class:`~datetime.datetime` will be rounded to the nearest days,
    if the :class:`~datetime.timedelta` is in hours the
    :class:`~datetime.datetime` will be rounded to the nearest hour,
    and so on until seconds, which will just return the original
    :class:`~datetime.datetime`.
    """
    ...

def remaining(start: datetime, ends_in: timedelta, now: datetime | None = ..., relative: bool = ...) -> timedelta:
    """Calculate the real remaining time for a start date and a timedelta.

    For example, "how many seconds left for 30 seconds after start?"

    Arguments:
        start (~datetime.datetime): Starting date.
        ends_in (~datetime.timedelta): The end delta.
        relative (bool): If enabled the end time will be calculated
            using :func:`delta_resolution` (i.e., rounded to the
            resolution of `ends_in`).
        now (~datetime.datetime): Current time and date.
            Defaults to :func:`datetime.now(timezone.utc)`.

    Returns:
        ~datetime.timedelta: Remaining time.
    """
    ...

def rate(r: str) -> float:
    """Convert rate string (`"100/m"`, `"2/h"` or `"0.5/s"`) to seconds."""
    ...

def weekday(name: str) -> int:
    """Return the position of a weekday: 0 - 7, where 0 is Sunday.

    Example:
        >>> weekday('sunday'), weekday('sun'), weekday('mon')
        (0, 0, 1)
    """
    ...

def yearmonth(name: str) -> int:
    """Return the position of a month: 1 - 12, where 1 is January.

    Example:
        >>> yearmonth('january'), yearmonth('jan'), yearmonth('may')
        (1, 1, 5)
    """
    ...

def humanize_seconds(secs: int, prefix: str = ..., sep: str = ..., now: str = ..., microseconds: bool = ...) -> str:
    """Show seconds in human form.

    For example, 60 becomes "1 minute", and 7200 becomes "2 hours".

    Arguments:
        prefix (str): can be used to add a preposition to the output
            (e.g., 'in' will give 'in 1 second', but add nothing to 'now').
        now (str): Literal 'now'.
        microseconds (bool): Include microseconds.
    """
    ...

def maybe_iso8601(dt: datetime | str | None) -> None | datetime:
    """Either ``datetime | str -> datetime`` or ``None -> None``."""
    ...

def is_naive(dt: datetime) -> bool:
    """Return True if :class:`~datetime.datetime` is naive, meaning it doesn't have timezone info set."""
    ...

def make_aware(dt: datetime, tz: tzinfo) -> datetime:
    """Set timezone for a :class:`~datetime.datetime` object."""
    ...

def localize(dt: datetime, tz: tzinfo) -> datetime:
    """Convert aware :class:`~datetime.datetime` to another timezone.

    Using a ZoneInfo timezone will give the most flexibility in terms of ambiguous DST handling.
    """
    ...

def to_utc(dt: datetime) -> datetime:
    """Convert naive :class:`~datetime.datetime` to UTC."""
    ...

def maybe_make_aware(dt: datetime, tz: tzinfo | None = ..., naive_as_utc: bool = ...) -> datetime:
    """Convert dt to aware datetime, do nothing if dt is already aware."""
    ...

class ffwd:
    """Version of ``dateutil.relativedelta`` that only supports addition."""
    def __init__(self, year=..., month=..., weeks=..., weekday=..., day=..., hour=..., minute=..., second=..., microsecond=..., **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __radd__(self, other: Any) -> timedelta:
        ...
    


def utcoffset(time: ModuleType = ..., localtime: Callable[..., _time.struct_time] = ...) -> float:
    """Return the current offset to UTC in hours."""
    ...

def adjust_timestamp(ts: float, offset: int, here: Callable[..., float] = ...) -> float:
    """Adjust timestamp based on provided utcoffset."""
    ...

def get_exponential_backoff_interval(factor: int, retries: int, maximum: int, full_jitter: bool = ...) -> int:
    """Calculate the exponential backoff wait time."""
    ...

