"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod
from kombu.utils.objects import cached_property
from celery.utils import abstract

"""Composing task work-flows.

.. seealso:

    You should import these from :mod:`celery` and not this module.
"""
__all__ = ('Signature', 'chain', 'xmap', 'xstarmap', 'chunks', 'group', 'chord', 'signature', 'maybe_signature')
def maybe_unroll_group(group):
    """Unroll group with only one member.
    This allows treating a group of a single task as if it
    was a single task without pre-knowledge."""
    ...

def task_name_from(task): # -> Any:
    ...

class StampingVisitor(metaclass=ABCMeta):
    """Stamping API.  A class that provides a stamping API possibility for
    canvas primitives. If you want to implement stamping behavior for
    a canvas primitive override method that represents it.
    """
    def on_group_start(self, group, **headers) -> dict:
        """Method that is called on group stamping start.

         Arguments:
             group (group): Group that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         Returns:
             Dict: headers to update.
         """
        ...
    
    def on_group_end(self, group, **headers) -> None:
        """Method that is called on group stamping end.

         Arguments:
             group (group): Group that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         """
        ...
    
    def on_chain_start(self, chain, **headers) -> dict:
        """Method that is called on chain stamping start.

         Arguments:
             chain (chain): Chain that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         Returns:
             Dict: headers to update.
         """
        ...
    
    def on_chain_end(self, chain, **headers) -> None:
        """Method that is called on chain stamping end.

         Arguments:
             chain (chain): Chain that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         """
        ...
    
    @abstractmethod
    def on_signature(self, sig, **headers) -> dict:
        """Method that is called on signature stamping.

         Arguments:
             sig (Signature): Signature that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         Returns:
             Dict: headers to update.
         """
        ...
    
    def on_chord_header_start(self, sig, **header) -> dict:
        """Method that is called on сhord header stamping start.

         Arguments:
             sig (chord): chord that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         Returns:
             Dict: headers to update.
         """
        ...
    
    def on_chord_header_end(self, sig, **header) -> None:
        """Method that is called on сhord header stamping end.

           Arguments:
               sig (chord): chord that is stamped.
               headers (Dict): Partial headers that could be merged with existing headers.
        """
        ...
    
    def on_chord_body(self, sig, **header) -> dict:
        """Method that is called on chord body stamping.

         Arguments:
             sig (chord): chord that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         Returns:
             Dict: headers to update.
        """
        ...
    
    def on_callback(self, callback, **header) -> dict:
        """Method that is called on callback stamping.

         Arguments:
             callback (Signature): callback that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         Returns:
             Dict: headers to update.
         """
        ...
    
    def on_errback(self, errback, **header) -> dict:
        """Method that is called on errback stamping.

         Arguments:
             errback (Signature): errback that is stamped.
             headers (Dict): Partial headers that could be merged with existing headers.
         Returns:
             Dict: headers to update.
         """
        ...
    


@abstract.CallableSignature.register
class Signature(dict):
    """Task Signature.

    Class that wraps the arguments and execution options
    for a single task invocation.

    Used as the parts in a :class:`group` and other constructs,
    or to pass tasks around as callbacks while being compatible
    with serializers with a strict type subset.

    Signatures can also be created from tasks:

    - Using the ``.signature()`` method that has the same signature
      as ``Task.apply_async``:

        .. code-block:: pycon

            >>> add.signature(args=(1,), kwargs={'kw': 2}, options={})

    - or the ``.s()`` shortcut that works for star arguments:

        .. code-block:: pycon

            >>> add.s(1, kw=2)

    - the ``.s()`` shortcut does not allow you to specify execution options
      but there's a chaining `.set` method that returns the signature:

        .. code-block:: pycon

            >>> add.s(2, 2).set(countdown=10).set(expires=30).delay()

    Note:
        You should use :func:`~celery.signature` to create new signatures.
        The ``Signature`` class is the type returned by that function and
        should be used for ``isinstance`` checks for signatures.

    See Also:
        :ref:`guide-canvas` for the complete guide.

    Arguments:
        task (Union[Type[celery.app.task.Task], str]): Either a task
            class/instance, or the name of a task.
        args (Tuple): Positional arguments to apply.
        kwargs (Dict): Keyword arguments to apply.
        options (Dict): Additional options to :meth:`Task.apply_async`.

    Note:
        If the first argument is a :class:`dict`, the other
        arguments will be ignored and the values in the dict will be used
        instead::

            >>> s = signature('tasks.add', args=(2, 2))
            >>> signature(s)
            {'task': 'tasks.add', args=(2, 2), kwargs={}, options={}}
    """
    TYPES = ...
    _type = ...
    _IMMUTABLE_OPTIONS = ...
    @classmethod
    def register_type(cls, name=...): # -> Callable[..., Any]:
        """Register a new type of signature.
        Used as a class decorator, for example:
        >>> @Signature.register_type()
        >>> class mysig(Signature):
        >>>     pass
        """
        ...
    
    @classmethod
    def from_dict(cls, d, app=...): # -> Signature:
        """Create a new signature from a dict.
        Subclasses can override this method to customize how are
        they created from a dict.
        """
        ...
    
    def __init__(self, task=..., args=..., kwargs=..., options=..., type=..., subtask_type=..., immutable=..., app=..., **ex) -> None:
        ...
    
    def __call__(self, *partial_args, **partial_kwargs):
        """Call the task directly (in the current process)."""
        ...
    
    def delay(self, *partial_args, **partial_kwargs): # -> None:
        """Shortcut to :meth:`apply_async` using star arguments."""
        ...
    
    def apply(self, args=..., kwargs=..., **options):
        """Call task locally.

        Same as :meth:`apply_async` but executed the task inline instead
        of sending a task message.
        """
        ...
    
    def apply_async(self, args=..., kwargs=..., route_name=..., **options): # -> None:
        """Apply this task asynchronously.

        Arguments:
            args (Tuple): Partial args to be prepended to the existing args.
            kwargs (Dict): Partial kwargs to be merged with existing kwargs.
            options (Dict): Partial options to be merged
                with existing options.

        Returns:
            ~@AsyncResult: promise of future evaluation.

        See also:
            :meth:`~@Task.apply_async` and the :ref:`guide-calling` guide.
        """
        ...
    
    def clone(self, args=..., kwargs=..., **opts): # -> Signature:
        """Create a copy of this signature.

        Arguments:
            args (Tuple): Partial args to be prepended to the existing args.
            kwargs (Dict): Partial kwargs to be merged with existing kwargs.
            options (Dict): Partial options to be merged with
                existing options.
        """
        ...
    
    partial = ...
    def freeze(self, _id=..., group_id=..., chord=..., root_id=..., parent_id=..., group_index=...):
        """Finalize the signature by adding a concrete task id.

        The task won't be called and you shouldn't call the signature
        twice after freezing it as that'll result in two task messages
        using the same task id.

        The arguments are used to override the signature's headers during
        freezing.

        Arguments:
            _id (str): Task id to use if it didn't already have one.
                New UUID is generated if not provided.
            group_id (str): Group id to use if it didn't already have one.
            chord (Signature): Chord body when freezing a chord header.
            root_id (str): Root id to use.
            parent_id (str): Parent id to use.
            group_index (int): Group index to use.

        Returns:
            ~@AsyncResult: promise of future evaluation.
        """
        ...
    
    _freeze = ...
    def replace(self, args=..., kwargs=..., options=...): # -> Signature:
        """Replace the args, kwargs or options set for this signature.

        These are only replaced if the argument for the section is
        not :const:`None`.
        """
        ...
    
    def set(self, immutable=..., **options): # -> Self:
        """Set arbitrary execution options (same as ``.options.update(…)``).

        Returns:
            Signature: This is a chaining method call
                (i.e., it will return ``self``).
        """
        ...
    
    def set_immutable(self, immutable): # -> None:
        ...
    
    def stamp(self, visitor=..., append_stamps=..., **headers): # -> Self:
        """Stamp this signature with additional custom headers.
        Using a visitor will pass on responsibility for the stamping
        to the visitor.

        .. versionadded:: 5.3

        Arguments:
            visitor (StampingVisitor): Visitor API object.
            append_stamps (bool):
                If True, duplicated stamps will be appended to a list.
                If False, duplicated stamps will be replaced by the last stamp.
            headers (Dict): Stamps that should be added to headers.
        """
        ...
    
    def stamp_links(self, visitor, append_stamps=..., **headers): # -> None:
        """Stamp this signature links (callbacks and errbacks).
        Using a visitor will pass on responsibility for the stamping
        to the visitor.

        Arguments:
            visitor (StampingVisitor): Visitor API object.
            append_stamps (bool):
                If True, duplicated stamps will be appended to a list.
                If False, duplicated stamps will be replaced by the last stamp.
            headers (Dict): Stamps that should be added to headers.
        """
        ...
    
    def append_to_list_option(self, key, value):
        """Appends the given value to the list at the given key in self.options."""
        ...
    
    def extend_list_option(self, key, value): # -> None:
        """Extends the list at the given key in self.options with the given value.

        If the value is not a list, it will be converted to one.
        """
        ...
    
    def link(self, callback):
        """Add callback task to be applied if this task succeeds.

        Returns:
            Signature: the argument passed, for chaining
                or use with :func:`~functools.reduce`.
        """
        ...
    
    def link_error(self, errback):
        """Add callback task to be applied on error in task execution.

        Returns:
            Signature: the argument passed, for chaining
                or use with :func:`~functools.reduce`.
        """
        ...
    
    def on_error(self, errback): # -> Self:
        """Version of :meth:`link_error` that supports chaining.

        on_error chains the original signature, not the errback so::

            >>> add.s(2, 2).on_error(errback.s()).delay()

        calls the ``add`` task, not the ``errback`` task, but the
        reverse is true for :meth:`link_error`.
        """
        ...
    
    def flatten_links(self): # -> list[Self]:
        """Return a recursive list of dependencies.

        "unchain" if you will, but with links intact.
        """
        ...
    
    def __or__(self, other): # -> _chain | NotImplementedType:
        """Chaining operator.

        Example:
            >>> add.s(2, 2) | add.s(4) | add.s(8)

        Returns:
            chain: Constructs a :class:`~celery.canvas.chain` of the given signatures.
        """
        ...
    
    def __ior__(self, other): # -> _chain | NotImplementedType:
        ...
    
    def election(self):
        ...
    
    def reprcall(self, *args, **kwargs): # -> str:
        """Return a string representation of the signature.

        Merges the given arguments with the signature's arguments
        only for the purpose of generating the string representation.
        The signature itself is not modified.

        Example:
            >>> add.s(2, 2).reprcall()
            'add(2, 2)'
        """
        ...
    
    def __deepcopy__(self, memo): # -> dict[Any, Any]:
        ...
    
    def __invert__(self):
        ...
    
    def __reduce__(self): # -> tuple[Callable[..., Any | Signature | None], tuple[dict[Any, Any]]]:
        ...
    
    def __json__(self): # -> dict[Any, Any]:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def items(self): # -> Generator[tuple[str | Any, Any], Any, None]:
        ...
    
    @property
    def name(self): # -> None:
        ...
    
    @cached_property
    def type(self):
        ...
    
    @cached_property
    def app(self): # -> Proxy:
        ...
    
    @cached_property
    def AsyncResult(self):
        ...
    
    id = ...
    parent_id = ...
    root_id = ...
    task = ...
    args = ...
    kwargs = ...
    options = ...
    subtask_type = ...
    immutable = ...


@Signature.register_type(name='chain')
class _chain(Signature):
    tasks = ...
    @classmethod
    def from_dict(cls, d, app=...): # -> Self:
        ...
    
    def __init__(self, *tasks, **options) -> None:
        ...
    
    def __call__(self, *args, **kwargs): # -> None:
        ...
    
    def __or__(self, other): # -> group | Self | Signature | NotImplementedType:
        ...
    
    def clone(self, *args, **kwargs): # -> Signature:
        ...
    
    def unchain_tasks(self): # -> list[Any]:
        """Return a list of tasks in the chain.

        The tasks list would be cloned from the chain's tasks.
        All of the chain callbacks would be added to the last task in the (cloned) chain.
        All of the tasks would be linked to the same error callback
        as the chain itself, to ensure that the correct error callback is called
        if any of the (cloned) tasks of the chain fail.
        """
        ...
    
    def apply_async(self, args=..., kwargs=..., **options): # -> None:
        ...
    
    def run(self, args=..., kwargs=..., group_id=..., chord=..., task_id=..., link=..., link_error=..., publisher=..., producer=..., root_id=..., parent_id=..., app=..., group_index=..., **options): # -> None:
        """Executes the chain.

        Responsible for executing the chain in the correct order.
        In a case of a chain of a single task, the task is executed directly
        and the result is returned for that task specifically.
        """
        ...
    
    def freeze(self, _id=..., group_id=..., chord=..., root_id=..., parent_id=..., group_index=...):
        ...
    
    def stamp(self, visitor=..., append_stamps=..., **headers): # -> None:
        ...
    
    def prepare_steps(self, args, kwargs, tasks, root_id=..., parent_id=..., link_error=..., app=..., last_task_id=..., group_id=..., chord_body=..., clone=..., from_dict=..., group_index=...): # -> tuple[list[Any], list[Any]]:
        """Prepare the chain for execution.

        To execute a chain, we first need to unpack it correctly.
        During the unpacking, we might encounter other chains, groups, or chords
        which we need to unpack as well.

        For example:
        chain(signature1, chain(signature2, signature3)) --> Upgrades to chain(signature1, signature2, signature3)
        chain(group(signature1, signature2), signature3) --> Upgrades to chord([signature1, signature2], signature3)

        The responsibility of this method is to ensure that the chain is
        correctly unpacked, and then the correct callbacks are set up along the way.

        Arguments:
            args (Tuple): Partial args to be prepended to the existing args.
            kwargs (Dict): Partial kwargs to be merged with existing kwargs.
            tasks (List[Signature]): The tasks of the chain.
            root_id (str): The id of the root task.
            parent_id (str): The id of the parent task.
            link_error (Union[List[Signature], Signature]): The error callback.
                will be set for all tasks in the chain.
            app (Celery): The Celery app instance.
            last_task_id (str): The id of the last task in the chain.
            group_id (str): The id of the group that the chain is a part of.
            chord_body (Signature): The body of the chord, used to synchronize with the chain's
                last task and the chord's body when used together.
            clone (bool): Whether to clone the chain's tasks before modifying them.
            from_dict (Callable): A function that takes a dict and returns a Signature.

        Returns:
            Tuple[List[Signature], List[AsyncResult]]: The frozen tasks of the chain, and the async results
        """
        ...
    
    def apply(self, args=..., kwargs=..., **options): # -> None:
        ...
    
    @property
    def app(self): # -> Proxy:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class chain(_chain):
    """Chain tasks together.

    Each tasks follows one another,
    by being applied as a callback of the previous task.

    Note:
        If called with only one argument, then that argument must
        be an iterable of tasks to chain: this allows us
        to use generator expressions.

    Example:
        This is effectively :math:`((2 + 2) + 4)`:

        .. code-block:: pycon

            >>> res = chain(add.s(2, 2), add.s(4))()
            >>> res.get()
            8

        Calling a chain will return the result of the last task in the chain.
        You can get to the other tasks by following the ``result.parent``'s:

        .. code-block:: pycon

            >>> res.parent.get()
            4

        Using a generator expression:

        .. code-block:: pycon

            >>> lazy_chain = chain(add.s(i) for i in range(10))
            >>> res = lazy_chain(3)

    Arguments:
        *tasks (Signature): List of task signatures to chain.
            If only one argument is passed and that argument is
            an iterable, then that'll be used as the list of signatures
            to chain instead.  This means that you can use a generator
            expression.

    Returns:
        ~celery.chain: A lazy signature that can be called to apply the first
            task in the chain.  When that task succeeds the next task in the
            chain is applied, and so on.
    """
    def __new__(cls, *tasks, **kwargs): # -> Self | _chain:
        ...
    


class _basemap(Signature):
    _task_name = ...
    _unpack_args = ...
    @classmethod
    def from_dict(cls, d, app=...): # -> Self:
        ...
    
    def __init__(self, task, it, **options) -> None:
        ...
    
    def apply_async(self, args=..., kwargs=..., **opts):
        ...
    


@Signature.register_type()
class xmap(_basemap):
    """Map operation for tasks.

    Note:
        Tasks executed sequentially in process, this is not a
        parallel operation like :class:`group`.
    """
    _task_name = ...
    def __repr__(self): # -> str:
        ...
    


@Signature.register_type()
class xstarmap(_basemap):
    """Map operation for tasks, using star arguments."""
    _task_name = ...
    def __repr__(self): # -> str:
        ...
    


@Signature.register_type()
class chunks(Signature):
    """Partition of tasks into chunks of size n."""
    _unpack_args = ...
    @classmethod
    def from_dict(cls, d, app=...): # -> Self:
        ...
    
    def __init__(self, task, it, n, **options) -> None:
        ...
    
    def __call__(self, **options): # -> Any:
        ...
    
    def apply_async(self, args=..., kwargs=..., **opts): # -> Any:
        ...
    
    def group(self): # -> group:
        ...
    
    @classmethod
    def apply_chunks(cls, task, it, n, app=...): # -> Any:
        ...
    


@Signature.register_type()
class group(Signature):
    """Creates a group of tasks to be executed in parallel.

    A group is lazy so you must call it to take action and evaluate
    the group.

    Note:
        If only one argument is passed, and that argument is an iterable
        then that'll be used as the list of tasks instead: this
        allows us to use ``group`` with generator expressions.

    Example:
        >>> lazy_group = group([add.s(2, 2), add.s(4, 4)])
        >>> promise = lazy_group()  # <-- evaluate: returns lazy result.
        >>> promise.get()  # <-- will wait for the task to return
        [4, 8]

    Arguments:
        *tasks (List[Signature]): A list of signatures that this group will
            call. If there's only one argument, and that argument is an
            iterable, then that'll define the list of signatures instead.
        **options (Any): Execution options applied to all tasks
            in the group.

    Returns:
        ~celery.group: signature that when called will then call all of the
            tasks in the group (and return a :class:`GroupResult` instance
            that can be used to inspect the state of the group).
    """
    tasks = ...
    @classmethod
    def from_dict(cls, d, app=...): # -> Self:
        """Create a group signature from a dictionary that represents a group.

        Example:
            >>> group_dict = {
                "task": "celery.group",
                "args": [],
                "kwargs": {
                    "tasks": [
                        {
                            "task": "add",
                            "args": [
                                1,
                                2
                            ],
                            "kwargs": {},
                            "options": {},
                            "subtask_type": None,
                            "immutable": False
                        },
                        {
                            "task": "add",
                            "args": [
                                3,
                                4
                            ],
                            "kwargs": {},
                            "options": {},
                            "subtask_type": None,
                            "immutable": False
                        }
                    ]
                },
                "options": {},
                "subtask_type": "group",
                "immutable": False
            }
            >>> group_sig = group.from_dict(group_dict)

        Iterates over the given tasks in the dictionary and convert them to signatures.
        Tasks needs to be defined in d['kwargs']['tasks'] as a sequence
        of tasks.

        The tasks themselves can be dictionaries or signatures (or both).
        """
        ...
    
    def __init__(self, *tasks, **options) -> None:
        ...
    
    def __call__(self, *partial_args, **options): # -> Any:
        ...
    
    def __or__(self, other): # -> chord:
        ...
    
    def skew(self, start=..., stop=..., step=...): # -> Self:
        ...
    
    def apply_async(self, args=..., kwargs=..., add_to_parent=..., producer=..., link=..., link_error=..., **options): # -> Any:
        ...
    
    def apply(self, args=..., kwargs=..., **options): # -> Any:
        ...
    
    def set_immutable(self, immutable): # -> None:
        ...
    
    def stamp(self, visitor=..., append_stamps=..., **headers): # -> None:
        ...
    
    def link(self, sig):
        ...
    
    def link_error(self, sig): # -> tuple[Any, ...]:
        ...
    
    def freeze(self, _id=..., group_id=..., chord=..., root_id=..., parent_id=..., group_index=...): # -> Any:
        ...
    
    _freeze = ...
    def __repr__(self): # -> str:
        ...
    
    def __len__(self): # -> int:
        ...
    
    @property
    def app(self): # -> Proxy:
        ...
    


@Signature.register_type(name="chord")
class _chord(Signature):
    r"""Barrier synchronization primitive.

    A chord consists of a header and a body.

    The header is a group of tasks that must complete before the callback is
    called.  A chord is essentially a callback for a group of tasks.

    The body is applied with the return values of all the header
    tasks as a list.

    Example:

        The chord:

        .. code-block:: pycon

            >>> res = chord([add.s(2, 2), add.s(4, 4)])(sum_task.s())

        is effectively :math:`\Sigma ((2 + 2) + (4 + 4))`:

        .. code-block:: pycon

            >>> res.get()
            12
    """
    @classmethod
    def from_dict(cls, d, app=...): # -> Self:
        """Create a chord signature from a dictionary that represents a chord.

        Example:
            >>> chord_dict = {
                "task": "celery.chord",
                "args": [],
                "kwargs": {
                    "kwargs": {},
                    "header": [
                        {
                            "task": "add",
                            "args": [
                                1,
                                2
                            ],
                            "kwargs": {},
                            "options": {},
                            "subtask_type": None,
                            "immutable": False
                        },
                        {
                            "task": "add",
                            "args": [
                                3,
                                4
                            ],
                            "kwargs": {},
                            "options": {},
                            "subtask_type": None,
                            "immutable": False
                        }
                    ],
                    "body": {
                        "task": "xsum",
                        "args": [],
                        "kwargs": {},
                        "options": {},
                        "subtask_type": None,
                        "immutable": False
                    }
                },
                "options": {},
                "subtask_type": "chord",
                "immutable": False
            }
            >>> chord_sig = chord.from_dict(chord_dict)

        Iterates over the given tasks in the dictionary and convert them to signatures.
        Chord header needs to be defined in d['kwargs']['header'] as a sequence
        of tasks.
        Chord body needs to be defined in d['kwargs']['body'] as a single task.

        The tasks themselves can be dictionaries or signatures (or both).
        """
        ...
    
    def __init__(self, header, body=..., task=..., args=..., kwargs=..., app=..., **options) -> None:
        ...
    
    def __call__(self, body=..., **options):
        ...
    
    def __or__(self, other): # -> Signature | _chain | NotImplementedType:
        ...
    
    def freeze(self, _id=..., group_id=..., chord=..., root_id=..., parent_id=..., group_index=...): # -> None:
        ...
    
    def stamp(self, visitor=..., append_stamps=..., **headers): # -> None:
        ...
    
    def apply_async(self, args=..., kwargs=..., task_id=..., producer=..., publisher=..., connection=..., router=..., result_cls=..., **options):
        ...
    
    def apply(self, args=..., kwargs=..., propagate=..., body=..., **options):
        ...
    
    def __length_hint__(self): # -> int:
        """Return the number of tasks in this chord's header (recursively)."""
        ...
    
    def run(self, header, body, partial_args, app=..., interval=..., countdown=..., max_retries=..., eager=..., task_id=..., kwargs=..., **options):
        """Execute the chord.

        Executing the chord means executing the header and sending the
        result to the body. In case of an empty header, the body is
        executed immediately.

        Arguments:
            header (group): The header to execute.
            body (Signature): The body to execute.
            partial_args (tuple): Arguments to pass to the header.
            app (Celery): The Celery app instance.
            interval (float): The interval between retries.
            countdown (int): The countdown between retries.
            max_retries (int): The maximum number of retries.
            task_id (str): The task id to use for the body.
            kwargs (dict): Keyword arguments to pass to the header.
            options (dict): Options to pass to the header.

        Returns:
            AsyncResult: The result of the body (with the result of the header in the parent of the body).
        """
        ...
    
    def clone(self, *args, **kwargs): # -> Signature:
        ...
    
    def link(self, callback):
        """Links a callback to the chord body only."""
        ...
    
    def link_error(self, errback): # -> CallableSignature | Signature | None:
        """Links an error callback to the chord body, and potentially the header as well.

        Note:
            The ``task_allow_error_cb_on_chord_header`` setting controls whether
            error callbacks are allowed on the header. If this setting is
            ``False`` (the current default), then the error callback will only be
            applied to the body.
        """
        ...
    
    def set_immutable(self, immutable): # -> None:
        """Sets the immutable flag on the chord header only.

        Note:
            Does not affect the chord body.

        Arguments:
            immutable (bool): The new mutability value for chord header.
        """
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @cached_property
    def app(self): # -> Proxy:
        ...
    
    tasks = ...
    body = ...


chord = _chord
def signature(varies, *args, **kwargs): # -> Signature | None:
    """Create new signature.

    - if the first argument is a signature already then it's cloned.
    - if the first argument is a dict, then a Signature version is returned.

    Returns:
        Signature: The resulting signature.
    """
    ...

subtask = ...
def maybe_signature(d, app=..., clone=...): # -> CallableSignature | Signature | None:
    """Ensure obj is a signature, or None.

    Arguments:
        d (Optional[Union[abstract.CallableSignature, Mapping]]):
            Signature or dict-serialized signature.
        app (celery.Celery):
            App to bind signature to.
        clone (bool):
            If d' is already a signature, the signature
           will be cloned when this flag is enabled.

    Returns:
        Optional[abstract.CallableSignature]
    """
    ...

maybe_subtask = ...
